# ============================================================
# Automatically generated by Autonomous FinOps Engine
# ⚠️  WARNING: These are idle/wasted resources.
# Review carefully before applying. Destruction is irreversible.
# ============================================================

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.5.0"
}

provider "google" {
  project = var.project_id
}

# ──────────────────────────────────────────────────────────────
# Resource : demo-unattached-disk-1
# Type     : google_compute_disk
# Location : us-central1-a
# Reason   : Unattached persistent disk (DEMO)
# Est. Cost: $4.00/month
# ──────────────────────────────────────────────────────────────

resource "google_compute_disk" "idle_demo_unattached_disk_1" {
  name    = "demo-unattached-disk-1"
  zone    = "us-central1-a"
  project = "my-finops-project"
}

import {
  to = google_compute_disk.idle_demo_unattached_disk_1
  id = "projects/my-finops-project/zones/us-central1-a/disks/demo-unattached-disk-1"
}

# ──────────────────────────────────────────────────────────────
# Resource : demo-unattached-disk-2
# Type     : google_compute_disk
# Location : us-central1-a
# Reason   : Old backup disk, never re-attached (DEMO)
# Est. Cost: $8.00/month
# ──────────────────────────────────────────────────────────────

resource "google_compute_disk" "idle_demo_unattached_disk_2" {
  name    = "demo-unattached-disk-2"
  zone    = "us-central1-a"
  project = "my-finops-project"
}

import {
  to = google_compute_disk.idle_demo_unattached_disk_2
  id = "projects/my-finops-project/zones/us-central1-a/disks/demo-unattached-disk-2"
}

# ──────────────────────────────────────────────────────────────
# Resource : demo-stopped-vm-1
# Type     : google_compute_instance
# Location : us-east1-b
# Reason   : VM detenida (TERMINATED) hace más de 14 días (DEMO)
# Est. Cost: $2.00/month
# ──────────────────────────────────────────────────────────────

resource "google_compute_instance" "idle_demo_stopped_vm_1" {
  name         = "demo-stopped-vm-1"
  machine_type = "n1-standard-1"
  zone         = "us-east1-b"
  project      = "my-finops-project"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-11"
    }
  }
  network_interface {
    network = "default"
  }
}

import {
  to = google_compute_instance.idle_demo_stopped_vm_1
  id = "projects/my-finops-project/zones/us-east1-b/instances/demo-stopped-vm-1"
}

# ──────────────────────────────────────────────────────────────
# Resource : demo-old-snapshot-1
# Type     : google_compute_snapshot
# Location : global
# Reason   : Snapshot obsoleto (más de 60 días) (DEMO)
# Est. Cost: $2.50/month
# ──────────────────────────────────────────────────────────────

resource "google_compute_snapshot" "idle_demo_old_snapshot_1" {
  name    = "demo-old-snapshot-1"
  project = "my-finops-project"
  source_disk = "placeholder"  # Actualizar con el disco fuente si se conoce
}

import {
  to = google_compute_snapshot.idle_demo_old_snapshot_1
  id = "projects/my-finops-project/global/snapshots/demo-old-snapshot-1"
}

# ──────────────────────────────────────────────────────────────
# Resource : demo-unused-ip-1
# Type     : google_compute_address
# Location : us-central1
# Reason   : IP externa estática reservada sin asignar (DEMO)
# Est. Cost: $7.20/month
# ──────────────────────────────────────────────────────────────

resource "google_compute_address" "idle_demo_unused_ip_1" {
  name    = "demo-unused-ip-1"
  region  = "us-central1"
  project = "my-finops-project"
}

import {
  to = google_compute_address.idle_demo_unused_ip_1
  id = "projects/my-finops-project/regions/us-central1/addresses/demo-unused-ip-1"
}

# ──────────────────────────────────────────────────────────────
# Resource : demo-unused-ip-2
# Type     : google_compute_address
# Location : europe-west1
# Reason   : IP externa estática (Legacy) sin asignar (DEMO)
# Est. Cost: $7.20/month
# ──────────────────────────────────────────────────────────────

resource "google_compute_address" "idle_demo_unused_ip_2" {
  name    = "demo-unused-ip-2"
  region  = "europe-west1"
  project = "my-finops-project"
}

import {
  to = google_compute_address.idle_demo_unused_ip_2
  id = "projects/my-finops-project/regions/europe-west1/addresses/demo-unused-ip-2"
}

# ──────────────────────────────────────────────────────────────
# Resource : demo-allow-ssh-world
# Type     : google_compute_firewall
# Location : global
# Reason   : Regla de firewall permite SSH (22) desde 0.0.0.0/0 — riesgo de seguridad (DEMO)
# Est. Cost: $1.00/month
# ──────────────────────────────────────────────────────────────

resource "google_compute_firewall" "risky_demo_allow_ssh_world" {
  name    = "demo-allow-ssh-world"
  network = "default"
  project = "my-finops-project"

  # ⚠️ Revisar y restringir las fuentes de esta regla antes de aplicar
  allow {
    protocol = "tcp"
  }
}

import {
  to = google_compute_firewall.risky_demo_allow_ssh_world
  id = "projects/my-finops-project/global/firewalls/demo-allow-ssh-world"
}

# ──────────────────────────────────────────────────────────────
# Resource : demo-empty-bucket-logs
# Type     : google_storage_bucket
# Location : us-central1
# Reason   : Bucket de Cloud Storage completamente vacío (DEMO)
# Est. Cost: $3.00/month
# ──────────────────────────────────────────────────────────────

resource "google_storage_bucket" "idle_demo_empty_bucket_logs" {
  name     = "demo-empty-bucket-logs"
  location = "US-CENTRAL1"
  project  = "my-finops-project"
}

import {
  to = google_storage_bucket.idle_demo_empty_bucket_logs
  id = "demo-empty-bucket-logs"
}

# ──────────────────────────────────────────────────────────────
# Resource : demo-inactive-bucket-backups
# Type     : google_storage_bucket
# Location : us-east1
# Reason   : Bucket sin actividad en más de 90 días (DEMO)
# Est. Cost: $3.00/month
# ──────────────────────────────────────────────────────────────

resource "google_storage_bucket" "idle_demo_inactive_bucket_backups" {
  name     = "demo-inactive-bucket-backups"
  location = "US-EAST1"
  project  = "my-finops-project"
}

import {
  to = google_storage_bucket.idle_demo_inactive_bucket_backups
  id = "demo-inactive-bucket-backups"
}

