# Automagically Generated by FinOps Engine
# ------------------------------------------------------------------
# WARNING: These are idle resources designated for remediation.
# Import them into state, review, and then delete the resource 
# definitions to destroy them via `terraform apply`.
# ------------------------------------------------------------------

provider "google" {
  project = var.project_id
}


# Target: demo-unattached-disk-1
# Reason: Unattached demo disk

resource "google_compute_disk" "idle_disk_demo_unattached_disk_1" {
  name    = "demo-unattached-disk-1"
  zone    = "us-central1-a"
  project = "my-finops-project"
  # Se pueden agregar dependencias de lifecycle (prevent_destroy) temporalmente si se requiere validación manual.
}

import {
  to = google_compute_disk.idle_disk_demo_unattached_disk_1
  id = "projects/my-finops-project/zones/us-central1-a/disks/demo-unattached-disk-1"
}



# Target: demo-unattached-disk-2
# Reason: Old backup demo disk

resource "google_compute_disk" "idle_disk_demo_unattached_disk_2" {
  name    = "demo-unattached-disk-2"
  zone    = "us-central1-a"
  project = "my-finops-project"
  # Se pueden agregar dependencias de lifecycle (prevent_destroy) temporalmente si se requiere validación manual.
}

import {
  to = google_compute_disk.idle_disk_demo_unattached_disk_2
  id = "projects/my-finops-project/zones/us-central1-a/disks/demo-unattached-disk-2"
}



# Target: demo-unused-ip-1
# Reason: Unused external static IP

resource "google_compute_address" "idle_ip_demo_unused_ip_1" {
  name    = "demo-unused-ip-1"
  region  = "us-central1"
  project = "my-finops-project"
}

import {
  to = google_compute_address.idle_ip_demo_unused_ip_1
  id = "projects/my-finops-project/regions/us-central1/addresses/demo-unused-ip-1"
}



# Target: demo-unused-ip-2
# Reason: Unused external static IP (Legacy)

resource "google_compute_address" "idle_ip_demo_unused_ip_2" {
  name    = "demo-unused-ip-2"
  region  = "us-central1"
  project = "my-finops-project"
}

import {
  to = google_compute_address.idle_ip_demo_unused_ip_2
  id = "projects/my-finops-project/regions/us-central1/addresses/demo-unused-ip-2"
}


